project_id = "dbnqnxgrjoqgifchqtua"

[functions.qbo-webhook]
verify_jwt = false

[functions.qbo-oauth]
verify_jwt = false

[functions.qbo-oauth-callback]
verify_jwt = false

[functions.qbo-api]
verify_jwt = false

[functions.run-financial-control-bot]
verify_jwt = false

[functions.run-crm-bot]
verify_jwt = false

[functions.send-report-email]
verify_jwt = false

[functions.test-webhook]
verify_jwt = false

[functions.jobber-oauth]
verify_jwt = false

[functions.jobber-oauth-callback]
verify_jwt = false

[functions.jobber-api]
verify_jwt = false

[functions.jobber-webhook]
verify_jwt = false

[functions.run-pete-scraper]
verify_jwt = false

[functions.labortech-api]
verify_jwt = false

[functions.trigger-scheduled-bots]
verify_jwt = false

[functions.slack-bot]
verify_jwt = false
