import {
  Users,
  Phone,
  Calendar,
  FileCheck,
  Building2,
  DollarSign,
  TrendingUp,
  Briefcase,
  PiggyBank,
  CreditCard,
  AlertCircle,
  ClipboardList,
  Hammer,
  Percent,
  Target,
  ShieldCheck,
  Wrench,
  BarChart3,
  Wallet,
  LucideIcon
} from 'lucide-react';
import type { CompanyType, CadenceType, KpiStatus } from '@/types/database';

export interface KpiDefinition {
  key: string;
  label: string;
  icon: LucideIcon;
  format: 'number' | 'currency' | 'percent';
  trendLabel: string;
}

export interface KpiValue {
  value: number | string;
  trend: number;
  status: KpiStatus;
}

// Financial Control Bot KPIs (applies to all companies)
// These match the KPIs generated by the run-financial-control-bot edge function
export const financialControlKpis: Record<CadenceType, KpiDefinition[]> = {
  daily: [
    // Universal KPIs (ALL companies) - from your specification
    { key: 'sales_revenue', label: 'Sales Revenue', icon: DollarSign, format: 'currency', trendLabel: 'today' },
    { key: 'gross_profit', label: 'Gross Profit', icon: TrendingUp, format: 'currency', trendLabel: 'today' },
    { key: 'net_profit', label: 'Net Profit', icon: PiggyBank, format: 'currency', trendLabel: 'today' },
    // Operational KPIs
    { key: 'net_cash_flow', label: 'Net Cash Flow', icon: Wallet, format: 'currency', trendLabel: 'today' },
    { key: 'categorization_rate', label: 'Categorization Rate', icon: Percent, format: 'percent', trendLabel: 'today' },
    { key: 'total_income', label: 'Total Income', icon: TrendingUp, format: 'currency', trendLabel: 'today' },
    { key: 'total_expenses', label: 'Total Expenses', icon: CreditCard, format: 'currency', trendLabel: 'today' },
    { key: 'transactions_processed', label: 'Transactions Processed', icon: ClipboardList, format: 'number', trendLabel: 'today' },
  ],
  weekly: [
    { key: 'sales_revenue', label: 'Sales Revenue', icon: DollarSign, format: 'currency', trendLabel: 'this week' },
    { key: 'gross_profit', label: 'Gross Profit', icon: TrendingUp, format: 'currency', trendLabel: 'this week' },
    { key: 'net_profit', label: 'Net Profit', icon: PiggyBank, format: 'currency', trendLabel: 'this week' },
    { key: 'net_cash_flow', label: 'Net Cash Flow', icon: Wallet, format: 'currency', trendLabel: 'this week' },
    { key: 'categorization_rate', label: 'Categorization Rate', icon: Percent, format: 'percent', trendLabel: 'this week' },
    { key: 'total_income', label: 'Total Income', icon: TrendingUp, format: 'currency', trendLabel: 'this week' },
    { key: 'total_expenses', label: 'Total Expenses', icon: CreditCard, format: 'currency', trendLabel: 'this week' },
    { key: 'transactions_processed', label: 'Transactions Processed', icon: ClipboardList, format: 'number', trendLabel: 'this week' },
  ],
  monthly: [
    { key: 'sales_revenue', label: 'Sales Revenue', icon: DollarSign, format: 'currency', trendLabel: 'this month' },
    { key: 'gross_profit', label: 'Gross Profit', icon: TrendingUp, format: 'currency', trendLabel: 'this month' },
    { key: 'net_profit', label: 'Net Profit', icon: PiggyBank, format: 'currency', trendLabel: 'this month' },
    { key: 'net_cash_flow', label: 'Net Cash Flow', icon: Wallet, format: 'currency', trendLabel: 'this month' },
    { key: 'categorization_rate', label: 'Categorization Rate', icon: Percent, format: 'percent', trendLabel: 'this month' },
    { key: 'total_income', label: 'Total Income', icon: TrendingUp, format: 'currency', trendLabel: 'this month' },
    { key: 'total_expenses', label: 'Total Expenses', icon: CreditCard, format: 'currency', trendLabel: 'this month' },
    { key: 'transactions_processed', label: 'Transactions Processed', icon: ClipboardList, format: 'number', trendLabel: 'this month' },
  ],
  quarterly: [
    { key: 'sales_revenue', label: 'Sales Revenue', icon: DollarSign, format: 'currency', trendLabel: 'this quarter' },
    { key: 'gross_profit', label: 'Gross Profit', icon: TrendingUp, format: 'currency', trendLabel: 'this quarter' },
    { key: 'net_profit', label: 'Net Profit', icon: PiggyBank, format: 'currency', trendLabel: 'this quarter' },
    { key: 'net_cash_flow', label: 'Net Cash Flow', icon: Wallet, format: 'currency', trendLabel: 'this quarter' },
    { key: 'categorization_rate', label: 'Categorization Rate', icon: Percent, format: 'percent', trendLabel: 'this quarter' },
    { key: 'total_income', label: 'Total Income', icon: TrendingUp, format: 'currency', trendLabel: 'this quarter' },
    { key: 'total_expenses', label: 'Total Expenses', icon: CreditCard, format: 'currency', trendLabel: 'this quarter' },
    { key: 'transactions_processed', label: 'Transactions Processed', icon: ClipboardList, format: 'number', trendLabel: 'this quarter' },
  ],
};

// Property Halo KPIs (from PETE CRM + Asset Summary)
// Data source: PETE CRM integration required
export const propertyHaloKpis: Record<CadenceType, KpiDefinition[]> = {
  daily: [
    { key: 'leads', label: 'Leads', icon: Users, format: 'number', trendLabel: 'vs yesterday' },
    { key: 'appointments', label: 'Appointments', icon: Calendar, format: 'number', trendLabel: 'vs yesterday' },
    { key: 'calls', label: 'Calls Made', icon: Phone, format: 'number', trendLabel: 'vs yesterday' },
    { key: 'completed_deals', label: 'Completed Deals', icon: Target, format: 'number', trendLabel: 'vs yesterday' },
  ],
  weekly: [
    { key: 'contracts_in_pipeline', label: 'Contracts in Pipeline', icon: Briefcase, format: 'number', trendLabel: 'vs last week' },
    { key: 'pipeline_value', label: 'Pipeline Value', icon: DollarSign, format: 'currency', trendLabel: 'vs last week' },
    { key: 'under_contract', label: 'Under Contract', icon: FileCheck, format: 'number', trendLabel: 'vs last week' },
    { key: 'upcoming_closings', label: 'Upcoming Closings', icon: Calendar, format: 'number', trendLabel: 'vs last week' },
  ],
  monthly: [
    // Asset Summary KPIs
    { key: 'assets_bought', label: 'Assets Bought', icon: Building2, format: 'number', trendLabel: 'this month' },
    { key: 'assets_sold', label: 'Assets Sold', icon: Building2, format: 'number', trendLabel: 'this month' },
    { key: 'under_contract_monthly', label: 'Under Contract', icon: FileCheck, format: 'number', trendLabel: 'this month' },
    { key: 'closings', label: 'Closings', icon: Building2, format: 'number', trendLabel: 'vs last month' },
    { key: 'completed_deals', label: 'Completed Deals', icon: Target, format: 'number', trendLabel: 'vs last month' },
  ],
  quarterly: [
    { key: 'roi', label: 'ROI', icon: TrendingUp, format: 'percent', trendLabel: 'vs last quarter' },
    { key: 'capital_deployed', label: 'Capital Deployed', icon: DollarSign, format: 'currency', trendLabel: 'vs last quarter' },
    { key: 'portfolio_valuation', label: 'Portfolio Valuation', icon: Building2, format: 'currency', trendLabel: 'vs last quarter' },
  ],
};

// Unique Painting KPIs
// Data source: Jobber integration - tracks COUNTS only (not monetary values)
// Financial metrics (revenue, profit) come from QuickBooks via Financial Control bot
export const uniquePaintingKpis: Record<CadenceType, KpiDefinition[]> = {
  daily: [
    { key: 'requests', label: 'Requests', icon: ClipboardList, format: 'number', trendLabel: 'today' },
    { key: 'quotes', label: 'Quotes', icon: FileCheck, format: 'number', trendLabel: 'today' },
    { key: 'jobs', label: 'Jobs', icon: Hammer, format: 'number', trendLabel: 'today' },
    { key: 'invoices', label: 'Invoices', icon: CreditCard, format: 'number', trendLabel: 'today' },
    { key: 'payments', label: 'Payments', icon: DollarSign, format: 'number', trendLabel: 'today' },
  ],
  weekly: [
    { key: 'requests', label: 'Requests', icon: ClipboardList, format: 'number', trendLabel: 'this week' },
    { key: 'quotes', label: 'Quotes', icon: FileCheck, format: 'number', trendLabel: 'this week' },
    { key: 'jobs', label: 'Jobs', icon: Hammer, format: 'number', trendLabel: 'this week' },
    { key: 'invoices', label: 'Invoices', icon: CreditCard, format: 'number', trendLabel: 'this week' },
    { key: 'payments', label: 'Payments', icon: DollarSign, format: 'number', trendLabel: 'this week' },
  ],
  monthly: [
    { key: 'requests', label: 'Requests', icon: ClipboardList, format: 'number', trendLabel: 'this month' },
    { key: 'quotes', label: 'Quotes', icon: FileCheck, format: 'number', trendLabel: 'this month' },
    { key: 'jobs', label: 'Jobs', icon: Hammer, format: 'number', trendLabel: 'this month' },
    { key: 'invoices', label: 'Invoices', icon: CreditCard, format: 'number', trendLabel: 'this month' },
    { key: 'payments', label: 'Payments', icon: DollarSign, format: 'number', trendLabel: 'this month' },
  ],
  quarterly: [
    { key: 'requests', label: 'Requests', icon: ClipboardList, format: 'number', trendLabel: 'this quarter' },
    { key: 'quotes', label: 'Quotes', icon: FileCheck, format: 'number', trendLabel: 'this quarter' },
    { key: 'jobs', label: 'Jobs', icon: Hammer, format: 'number', trendLabel: 'this quarter' },
    { key: 'invoices', label: 'Invoices', icon: CreditCard, format: 'number', trendLabel: 'this quarter' },
    { key: 'payments', label: 'Payments', icon: DollarSign, format: 'number', trendLabel: 'this quarter' },
  ],
};

// ATI Security KPIs
// Data source: Jobber integration - tracks COUNTS only (not monetary values)
// Financial metrics (revenue, profit) come from QuickBooks via Financial Control bot
export const atiSecurityKpis: Record<CadenceType, KpiDefinition[]> = {
  daily: [
    { key: 'requests', label: 'Requests', icon: ClipboardList, format: 'number', trendLabel: 'today' },
    { key: 'quotes', label: 'Quotes', icon: FileCheck, format: 'number', trendLabel: 'today' },
    { key: 'jobs', label: 'Jobs', icon: Hammer, format: 'number', trendLabel: 'today' },
    { key: 'invoices', label: 'Invoices', icon: CreditCard, format: 'number', trendLabel: 'today' },
    { key: 'payments', label: 'Payments', icon: DollarSign, format: 'number', trendLabel: 'today' },
  ],
  weekly: [
    { key: 'requests', label: 'Requests', icon: ClipboardList, format: 'number', trendLabel: 'this week' },
    { key: 'quotes', label: 'Quotes', icon: FileCheck, format: 'number', trendLabel: 'this week' },
    { key: 'jobs', label: 'Jobs', icon: Hammer, format: 'number', trendLabel: 'this week' },
    { key: 'invoices', label: 'Invoices', icon: CreditCard, format: 'number', trendLabel: 'this week' },
    { key: 'payments', label: 'Payments', icon: DollarSign, format: 'number', trendLabel: 'this week' },
  ],
  monthly: [
    { key: 'requests', label: 'Requests', icon: ClipboardList, format: 'number', trendLabel: 'this month' },
    { key: 'quotes', label: 'Quotes', icon: FileCheck, format: 'number', trendLabel: 'this month' },
    { key: 'jobs', label: 'Jobs', icon: Hammer, format: 'number', trendLabel: 'this month' },
    { key: 'invoices', label: 'Invoices', icon: CreditCard, format: 'number', trendLabel: 'this month' },
    { key: 'payments', label: 'Payments', icon: DollarSign, format: 'number', trendLabel: 'this month' },
  ],
  quarterly: [
    { key: 'requests', label: 'Requests', icon: ClipboardList, format: 'number', trendLabel: 'this quarter' },
    { key: 'quotes', label: 'Quotes', icon: FileCheck, format: 'number', trendLabel: 'this quarter' },
    { key: 'jobs', label: 'Jobs', icon: Hammer, format: 'number', trendLabel: 'this quarter' },
    { key: 'invoices', label: 'Invoices', icon: CreditCard, format: 'number', trendLabel: 'this quarter' },
    { key: 'payments', label: 'Payments', icon: DollarSign, format: 'number', trendLabel: 'this quarter' },
  ],
};

// Get KPIs for a specific company type
export function getCompanyKpis(companyType: CompanyType): Record<CadenceType, KpiDefinition[]> {
  switch (companyType) {
    case 'property_halo':
      return propertyHaloKpis;
    case 'unique_painting':
      return uniquePaintingKpis;
    case 'ati_security':
      return atiSecurityKpis;
    default:
      return propertyHaloKpis;
  }
}

// Format value based on type
export function formatKpiValue(value: number | string, format: 'number' | 'currency' | 'percent'): string {
  if (typeof value === 'string') return value;
  
  switch (format) {
    case 'currency':
      return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
        minimumFractionDigits: 0,
        maximumFractionDigits: 0,
      }).format(value);
    case 'percent':
      return `${value.toFixed(1)}%`;
    case 'number':
    default:
      return new Intl.NumberFormat('en-US').format(value);
  }
}
